version: '3.9'

services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=order-delivery
    ports:
      - '5432:5432'

  discovery-service:
    container_name: discovery-service
    image: discovery-service
    build:
      context: discovery-service
      dockerfile: ./discovery-service/Dockerfile
    ports:
      - "8761:8761"
    depends_on:
      - postgres

  api-gateway:
    container_name: api-gateway
    image: api-gateway
    build:
      context: api-gateway
      dockerfile: ./api-gateway/Dockerfile
    ports:
      - "8090:8090"
    depends_on:
      - postgres
      - discovery-service

  delivery-service:
    container_name: order-delivery-ms
    image: order-delivery-ms
    build:
      context: order-delivery-ms
      dockerfile: ./order-delivery-ms/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - order-delivery-ms
      - api-gateway
